### ISSUE TITLE
empty message when passing options to the pnotify() helper

### ISSUE THREAD

**Issue by jamesj2** [php-flasher/flasher-pnotify-laravel#5]
Messages are not displaying when passing options to the pnotify() helper.  For the messages that work, the message is in the envelope object twice.  As the message and as an option.   For the message that doesn't work when passing an options array, there is no message in the options and it has a 'pnotify' key.

This works:
`pnotify('No options','success');`

This does not work:
`pnotify('Options','success',["delay" => 1000]);`

Result:
`Flasher.getInstance().render({"envelopes":[{"notification":{"type":"success","message":"No options message","options":{"text":"No options message"}},"handler":"pnotify","created_at":"2021-08-21 14:02:41","priority":0},{"notification":{"type":"success","message":"Options message","options":{"delay":1000}},"handler":"pnotify","created_at":"2021-08-21 14:02:41","priority":0}],"scripts":[],"styles":[],"options":{"pnotify":{"delay":1000}}});
`

**Comment by yoeunes** [comment]
Hello @jamesj2 can you please upgrade to v0.4.10 and check if it works ?

**Comment by jamesj2** [comment]
Updated and tested.  It's working as expected.  Thanks!
